cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_home, name='home'),
    url(r'^add/$', views.add_to_cart, name='add-list'),
    url(r'^update/$', views.UpdateCartView.as_view(), name='update'),  # Product Detail View
    url(r'^update-cart/$', views.cart_update_view, name='update-cart'),  # Update cart form
    url(r'^remove/$', views.cart_remove, name='remove'),
    url(r'^checkout/$', views.checkout_home, name='checkout'),
    url(r'^checkout/coupon/$', views.use_coupon_code, name='coupon'),
    url(r'^checkout/finalize/$', views.checkout_finalize, name='finalize'),
    url(r'^checkout/success/$', views.checkout_success, name='success'),
    url(r'^checkout/invoice/$', views.show_order_invoice, name='invoice'),
]

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartUpdateForm(forms.Form):
    size = forms.Select(choices="")
    quantity = forms.IntegerField(max_value=10, min_value=1)

cart/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.conf import settings
from django.contrib import messages
from django.views.generic import RedirectView

from accounts.forms import LoginForm, GuestForm
from addresses.forms import CheckoutAddressForm
from addresses.models import Address
from billing.models import BillingProfile
from orders.models import Order, OrderItem  # , GenerateOrderPdf
from store.models import Product, Variation
from .cart import Cart
from .models import CouponCode, UsedCoupon


# Paystack
site_id = getattr(settings, "SITE_ID")
if site_id == 1:
    test_paystack = getattr(settings, "PAYSTACK_SECRET_TEST_KEY")
    test_paystack_pk = getattr(settings, "PAYSTACK_PUB_TEST_KEY")

    live_paystack_secret = getattr(settings, "PAYSTACK_SECRET_LIVE_KEY")
    live_paystack_pk = getattr(settings, "PAYSTACK_PUB_LIVE_KEY")
else:
    test_paystack = getattr(settings, "PAYSTACK_SECRET_TEST_KEY")
    test_paystack_pk = getattr(settings, "PAYSTACK_PUB_TEST_KEY")

# Create your views here.
def cart_detail_api_view(request):
    cart = Cart(request)  # //
    cart_total = cart.get_total()
    cart_weight = cart.get_weight()
    action_update = "/cart/update/"
    action_remove = "{% url 'cart:remove' %}"

    products = []
    for item in cart.get_items():
        products.append({
            'id': item['id'],
            'sku': item['sku'],
            'url': item['url'],
            'title': item['title'],
            'brand': item['brand'],
            'image': item['image'],
            'size': item['size'],
            'quantity': item['quantity'],
            'price': item['price'],
            'slot': item['slot'],
            'attribute': str(item['attribute']),
        })
    print(products)

    json_data = {
        "cartTotal": cart_total,
        "cartWeight": cart_weight,
        "product": products,
        "action_update": action_update,
        "action_remove": action_remove
    }
    return JsonResponse(json_data)


def add_to_cart(request):
    product_id = request.POST.get('product_id', None)
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            print("Show message to user; Product is gone")
            return redirect("cart:home")
        cart_obj = Cart(request)

        cart_obj.add(product=product_obj, quantity=1)

        added = True
        removed = False
        cart_count = cart_obj.__len__()

        if request.is_ajax():
            print("Ajax request")
            json_data = {
                "added": added,
                "removed": removed,
                "cartCount": cart_count
            }
            return JsonResponse(json_data)
    return redirect("cart:home")


class UpdateCartView(RedirectView):
    def post(self, request, *args, **kwargs):
        request = self.request
        cart_obj = Cart(request)
        data = request.POST
        product_id = data.get('product_id')
        product_size_id = data.get('product', None)
        product_quantity = data.get('product_quantity')
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            print("Show message to user; Product is gone")
            return redirect("cart:home")

        size, stock = Variation.objects.get_size(product_obj, product_size_id)
        print(size, stock)

        # Take inventory
        msg = "Only " + str(stock) + " items in stock."
        check_stock = int(stock) - int(product_quantity)
        if check_stock < 0:
            messages.error(request, msg)
            return self.get_success_url(product_obj, product_quantity)

        cart_obj.add(product=product_obj, size=size, quantity=product_quantity, update_quantity=True)
        return self.get_success_url(product_obj, product_quantity)

    def get_success_url(self, product_obj, product_quantity):
        request = self.request
        cart_obj = Cart(request)
        product_value = product_obj.price * int(product_quantity)
        cart_count = cart_obj.__len__()
        if request.is_ajax():
            json_data = {
                "cartCount": cart_count,
                "productSKU": product_obj.sku,
                "productName": product_obj.title,
                "productPrice": product_obj.price,
                "productQuantity": product_quantity,
                "contentValue": product_value
            }
            return JsonResponse(json_data)
        return reverse("store:detail", kwargs={'slug': product_obj.slug})


def cart_update_view(request):
    product_id = request.POST.get('id', None)
    product_size = request.POST.get('size', None)
    product_quantity = request.POST.get('quantity', None)

    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            print("Show message to user; Product is gone")
            return redirect("cart:home")
        cart_obj = Cart(request)

        cart_obj.add(
            product=product_obj, size=product_size,
            quantity=product_quantity, update_quantity=True
        )

        cart_count = cart_obj.__len__()
        if request.is_ajax():
            print("Ajax request")
            json_data = {
                "cartCount": cart_count
            }
            return JsonResponse(json_data)
        return redirect("cart:home")


def cart_remove(request):
    print(request.POST)
    product_id = request.POST.get('product_id', None)
    product_slot = request.POST.get('product_slot', None)
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            print("Show message to user; Product is gone")
            return redirect("cart:home")
        cart_obj = Cart(request)
        cart_obj.remove(product=product_obj, slot=product_slot)
        added = False
        removed = True
        cart_count = cart_obj.__len__()
        if request.is_ajax():
            print("Ajax request")
            json_data = {
                "added": added,
                "removed": removed,
                "cartCount": cart_count
            }
            return JsonResponse(json_data)
    return redirect("cart:home")


def cart_home(request):
    return render(request, "cart/cart-home.html", {})


def checkout_home(request):
    cart_obj = Cart(request)
    if cart_obj.__len__() == 0:
        return redirect("cart:home")

    address_book = None
    login_form = LoginForm(request=request)
    guest_form = GuestForm(request=request)

    # Get cart total from POST request
    cart_total = request.POST.get('cart_total', None)

    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    order_obj, order_obj_created = Order.objects.new_or_get(billing_profile)

    if billing_profile is not None:
        address_book = Address.objects.all().filter(billing_profile=billing_profile)

    if cart_total is not None:
        # Calculate totals
        Order.objects.cart_total(request, obj=order_obj)

        # Remove Applied Coupon if any.
        if order_obj.coupon_applied is True:
            coupon = None
            try:
                coupon = order_obj.coupon
            except:
                pass

            if coupon:
                # Remove Coupon
                CouponCode.objects.remove_coupon(billing_profile, coupon, order_obj)

    # If Coupon, pass coupon_code  to the template and state if percentage discount
    coupon = None
    discount_type = None
    if order_obj.coupon:
        coupon = order_obj.coupon
        discount_type = request.session.get("discount_type", None)  # from session

    context = {
        "billing_profile": billing_profile,
        "login_form": login_form,
        "guest_form": guest_form,
        "address_book": address_book,
        "form": CheckoutAddressForm,
        "order_obj": order_obj,
        "coupon": coupon,
        "discount_type": discount_type
    }
    return render(request, "cart/checkout.html", context)


def use_coupon_code(request):
    user = request.user
    coupon_code = request.POST.get('coupon_code', None)

    if user.is_authenticated:
        billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile)

        if coupon_code is not None:
            CouponCode.objects.apply_coupon(request, billing_profile, coupon_code, order_obj)

        return redirect('cart:checkout')


def checkout_finalize(request):
    cart_obj = Cart(request)
    if cart_obj.__len__() == 0:
        return redirect("cart:home")

    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    order_obj, order_obj_created = Order.objects.new_or_get(billing_profile)
    address_book = Address.objects.all().filter(billing_profile=billing_profile)

    shipping_address_id = request.session.get("shipping_address_id", None)

    if order_obj.coupon:
        order_obj.coupon_applied = True

    if shipping_address_id:
        qs = address_book.filter(id=shipping_address_id)
        if qs.count() == 1:
            shipping_address = qs.first()

            if billing_profile is not None and shipping_address:
                order_obj.shipping_address = shipping_address
                order_obj.save()

        raw_order_total = int(order_obj.total)
        formatted_order_total = str(raw_order_total) + str('00')
        order_total = int(formatted_order_total)

        # If Coupon, pass coupon_code  to the template and state if percentage discount
        coupon = None
        discount_type = None
        if order_obj.coupon:
            coupon = order_obj.coupon

cart/templates/cart/cart-home.html
{% extends "base.html" %}
{% load static %}


{% block content %}

<section class="cart text-center">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="mt-5 mb-2">Your Shopping Cart</h2>
                <p class="mb-5"><span class="navbar-cart-count primary-color">{{ cart|length }}</span> Items in your cart</p>
                <table id="cart" class="table table-condensed cart-table" >
                    {% if cart|length > 0 %}

                    <thead>
                    <tr>
                        <th style="width:48%">Product</th>
                        <th style="width:12%">Size</th>
                        <th style="width:12%">Price</th>
                        <th style="width:12%">Quantity</th>
                        <th style="width:16%"></th>
                    </tr>
                    </thead>

                    <tbody class="cart-body">
                    {% for item in cart.get_items %}
                    {% with product=item.product %}

                    <tr class="cart-products">
                        <td data-th="Product">
                            <div class="row">
                                <div  class="cart-img-product b-rad-4 ">  <!--class="col-md-3 text-left" -->
                                    <a href="{{ product.get_absolute_url }}">
                                        <img src="{{ product.image_a.url }}" alt="IMG-PRODUCT">
                                    </a>
                                </div>
                                <div class="col-md-9 text-left mt-sm-2">
                                    <h4><a href="{{ product.get_absolute_url }}" class="block2-name"> {{ product.title }} </a></h4>
                                    <p>{{ product.brand }}</p>
                                </div>
                            </div>
                        </td>

                        <td data-th="Size">{{ item.size }}</td>

                        <td data-th="Price">₦{{ product.price }}</td>

                        <td data-th="Quantity">
                            {% include 'cart/snippets/cart-product-update.html' with id=product.id quantity=item.quantity size=item.size %}
                        </td>

                        <td class="actions">
                            {% include 'cart/snippets/cart-product-remove.html' with product_id=product.id product_slot=item.slot %}
                        </td>

                    </tr>

                    {% endwith %}
                    {% endfor %}

                    </tbody>
                    {% else %}
                    <tr class="cart-store">
                        <td class="col"><p class="lead text-center">Cart is empty</p></td>
                    </tr>
                    {% endif %}
                </table>

                <!--Hidden Update Component-->
                <div class="cart-item-update-form" style="display: none">
                    {% include 'cart/snippets/cart-product-update.html' %}
                </div>

                <!--Hidden Remove Component-->
                <div class="cart-item-remove-form" style="display: none">
                    {% include 'cart/snippets/cart-product-remove.html' %}
                </div>


                <!--Cart Totals-->
                <div class="cart-totals bo9 w-size18 p-l-40 p-r-40 p-t-30 p-b-38 m-b-100 m-t-30 m-r-0 m-l-auto p-lr-15-sm">
                    <h5 class="m-text20 p-b-24">
                        Cart Totals
                    </h5>

                    <!--  -->
                    <div class="flex-w flex-sb-m p-b-12">
                        <span class="s-text18 w-size19 w-full-sm">
                            Total:
                        </span>
                        <span class="cart-total m-text21 w-size20 w-full-sm">
                            ₦{{ cart.get_total }}
                        </span>
                    </div>
                    <div class="flex-w flex-sb bo10 p-t-15 p-b-20">

                        <form class="size10 trans-0-2 m-t-10 m-b-10 mx-auto" method="POST" action="{% url 'cart:checkout' %}">
                            {% csrf_token %}
                            <input type='hidden' name='cart_weight' value='{{ cart.get_weight }}' />
                            <input type='hidden' name='cart_total' value='{{ cart.get_total }}' />
                            <!-- Button -->
                            <button class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4" type="submit">
                                CHECKOUT
                            </button>
                        </form>
                    </div>
                </div>

                <div class="size11 m-r-10 mb-5 mb-m-3 text-md-left m-t-50">
                    <form class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4" method="GET" action="{{ store_url }}">
                        <button class="flex-c-m size2 bo-rad-23 s-text1 bgblack hov1 trans-0-4">
                            <i class="fa fa-arrow-left mr-2"></i> Continue Shopping
                        </button>
                    </form>
                </div>
            </div>
        </div>

    </div>
</section>

<div class="divider"></div>

{% endblock %}

cart/templates/cart/checkout-success.html
{% extends "base.html" %}


{% block content %}
<section class="banner2 bg5 p-t-55 p-b-55 m-b-50">
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-md-8 col-lg-6 m-l-r-auto p-t-15 p-b-15">
        <div class=" py-3">
          <h3 class="m-text5 t-center">
            Thank you for your order!
          </h3>
          <p class="t-center w-size4 mx-auto">
            Your order is currently being processed.<br/>
            You can view your invoice below.
            Also note that a copy of your invoice has been sent to your registered email.
            Thank you once again for choosing <b><a href="{{ home_url }}">1OVER3</a></b>
          </p>
          <form class="size10 trans-0-2 m-t-10 m-b-10 mx-auto" method="POST" action="{% url 'cart:invoice' %}">
            {% csrf_token %}
            <!-- Button -->
            <input type="hidden" name="order_id" value="{{ object.id }}">
            <button class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4" type="submit">
              Invoice
            </button>
          </form>
        </div>
      </div>

      <div class="col-sm-10 col-md-8 col-lg-6 m-l-r-auto p-t-15 p-b-15">
        <div class="bgwhite py-3">
          <h4 class="m-text4 t-center"> Hey There, </h4>
          <p class="t-center w-size4 mx-auto">
            It makes us happy when you spread the word. --- We want it to make you happy too! <br/>
            *** Follow us on instagram
            <a href="https://www.instagram.com/oneoverthree.store/" class="fs-18 color1 p-r-20 fa fa-instagram"></a> <br/>
            <a href="https://www.instagram.com/oneoverthree.store/">@oneoverthree.store</a>
            <i class="fa fa-hand-o-left"></i>
            <br/>
            *** Tag us wearing any of our outfits <i class="fa fa-tshirt"></i> <br/>
            *** Get your post featured on our page and get <b>20%</b> of your next order.
          </p>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Shipping -->
{% include 'base/shipping.html' %}

{% endblock %}




{% block js %}

<script>
    $(document).ready(function(){
        var actionEndPoint = '/api/checkout/complete/';
        var apiMethod = "GET";
        var data = {};

        $.ajax({
            url: actionEndPoint,
            method: apiMethod,
            data: data,
            success: function(data){
                var contents = [];
                $.each(data.product, function (index, value) {
                    contents.push(
                        {
                            id: value.sku,
                            quantity: value.quantity,
                            item_price: value.price
                        }
                    )
                });

                console.log(contents);

                fbq('track', 'Purchase', {
                    content_name: "New Pending Order",
                    content_type: "product_group",
                    contents: contents,
                    currency: "NGN",
                    value: data.cartTotal
                });
            },
            error: function (errorData) {
                console.log("error");
                console.log(errorData)
            }
        });
    });
</script>


{% endblock %}

cart/templates/cart/checkout.html
{% extends "base.html" %}
{% load static %}


{% block content %}

<section class="cart text-center">
    <div class="container m-b-150">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="mt-5 mb-2">Your Shopping Cart</h2>
                <p class="mb-5"><span class="primary-color">{{ cart|length }}</span> Items in your cart</p>

                <!--Cart Table-->
                {% include 'cart/snippets/checkout-cart-table.html' %}

                <!--Coupon code-->
                <div class="bo9 w-size18 p-l-40 p-r-40 p-t-30 p-b-38 m-t-30 m-r-0 m-b-100 m-l-auto p-lr-15-sm">
                    <form method="POST" action="{% url 'cart:coupon' %}">
                        {% csrf_token %}
                        <div class="flex-w flex-m w-full-sm">
                            <div class="size15 bo4 m-r-10">
                                <input class="sizefull s-text7 p-l-22 p-r-22" type="text" name="coupon_code" placeholder="Coupon Code" required="required">
                            </div>

                            <div class="size12 trans-0-4 m-t-10 m-b-10 m-r-10">
                                <!-- Button -->
                                <button class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4">
                                    Apply coupon
                                </button>
                            </div>
                        </div>
                        <!--Cart Total-->
                        <input type='hidden' name='cart_total' value='{{ cart.get_total }}' />
                    </form>
                    {% if order_obj.coupon %}
                    <div class="flex-w flex-sb-m p-t-12">
                        <span class="s-text18 w-full">
                            Coupon Code: <span class="txt2">{{ coupon }}</span>
                            Applied <i class="fa fa-check"></i>
                        </span>
                    </div>
                    {% endif %}
                </div>


                <!--Cart Totals-->
                <div class="bo9 w-size18 p-l-40 p-r-40 p-t-30 p-b-38 m-t-30 m-r-0 m-b-100 m-l-auto p-lr-15-sm">
                    <h5 class="m-text20 p-b-24">
                        Checkout
                    </h5>

                    <!--  -->
                    <div class="flex-w flex-sb-m p-b-12">
                        <span class="s-text18 w-size19 w-full-sm">
                            Cart Total:
                        </span>
                        <span class="m-text21 w-size20 w-full-sm">
                            ₦{{ cart.get_total }}
                        </span>
                    </div>

                    {% if order_obj.coupon %}
                    <div class="flex-w flex-sb-m bo10 p-t-12 p-b-12">
                        <span class="s-text18 w-size19 w-full-sm">
                            Discount <br>to Apply:
                        </span>
                        {% if discount_type == 2 %}
                        <span class="m-text21 w-size20 w-full-sm" style='color:#B22222'>
                            {{ order_obj.discount_applied }}%
                        </span>
                        {% else %}
                        <span class="m-text21 w-size20 w-full-sm" style='color:#B22222'>
                            -₦{{ order_obj.discount_applied }}
                        </span>
                        {% endif %}
                    </div>
                    {% endif %}

                    {% if not billing_profile %}

                    <!-- Create Billing Profile -->
                    <div class="flex-w flex-sb bo10 p-t-15 p-b-20">
                        <span class="s-text18 w-full w-full-sm">
                            Login
                        </span>

                        <div class="w-full w-full-sm">
                            {% include 'accounts/snippets/login_form.html' with form=login_form next_url=request.build_absolute_uri %}
                        </div>
                        <span class="s-text18 w-full w-full-sm mt-5">
                            Continue as Guest
                        </span>
                        <div class="w-full w-full-sm">
                            {% url "guest_register" as guest_register_url %}
                            {% include 'accounts/snippets/login_form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
                        </div>
                    </div>

                    {% else %}
                    <!-- Add Shipping Address -->
                    <div class="flex-w flex-sb bo10 p-t-15 p-b-20">
                        <span class="s-text18 w-size19 w-full-sm m-t-15">
                            Use Address:
                        </span>

                        <div class="w-full w-full-sm">
                            {% url 'checkout_finalize' as checkout_finalize %}
                            {% include 'addresses/checkout-saved-addresses.html' %}
                        </div>
                        <!--Add Address-->
                        <span class="s-text18 w-size19 w-full-sm m-t-30 mx-auto">
                            Add Address:
                        </span>
                        <div class="w-full w-full-sm">
                            {% url 'checkout_address_create' as checkout_address_create %}
                            {% include 'addresses/checkout-address-form.html' %}
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>

<div class="divider"></div>


{% endblock %}