accounts/passwords/urls.py
# accounts.passwords.urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^password/change/$',
        auth_views.PasswordChangeView.as_view(),
        name='password_change'),
    url(r'^password/change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),
    url(r'^password/reset/$',
        auth_views.PasswordResetView.as_view(),
        name='password_reset'),
    url(r'^password/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^password/reset/\
        (?P<uidb64>[0-9A-Za-z_\-]+)/\
        (?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^password/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
]

accounts/urls.py
from django.conf.urls import url, include

from dashboard.views import DashboardHomeView, OrderProcessingView

from marketing.views import MarketingPreferenceUpdateView, subscribe_to_notifications

from store.views import UserProductHistoryView

from orders.views import OrderListView, OrderDetailView, OrderCompletedView

from . import views

app_name = 'accounts'

urlpatterns = [

    url(r'^$', views.AccountHomeView.as_view(), name='home'),

    url(r'^details/$', views.AccountDetailsView.as_view(), name='details'),
    url(r'^details/update/$', views.UserDetailUpdateView.as_view(), name='details-update'),

    url(r'^dashboard/', include("dashboard.urls", namespace='dashboard')),

    url(r'^email/resend-activation/$', views.AccountEmailActivateView.as_view(), name='resend-activation'),
    url(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', views.AccountEmailActivateView.as_view(), name='email-activate'),

    url(r'^history/products/$', UserProductHistoryView.as_view(), name='user-product-history'),

    url(r'^orders/$', OrderListView.as_view(), name='orders'),
    url(r'^orders/order-update/$', OrderCompletedView.as_view(), name='order-complete'),
    url(r'^orders/(?P<order_id>[0-9A-Za-z]+)/$', OrderDetailView.as_view(), name='order-details'),

    # url(r'^settings/$', views.AccountSettingsView.as_view(), name='settings'),
    url(r'^settings/$', MarketingPreferenceUpdateView.as_view(), name='newsletter-subscribe-update'),
    url(r'^settings/newsletter/$', subscribe_to_notifications, name='newsletter-subscribe'),
]

addresses/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from . import views


app_name = 'addresses'

urlpatterns = [
    url(r'^$', views.AddressListView.as_view(), name='book'),
    url(r'^create/$', views.AddressCreateView.as_view(), name='create'),
    url(r'^checkout/re-use/$', views.CheckoutAddressReUseView.as_view(), name='checkout-re-use'),
    url(r'^checkout/create/$', views.CheckoutAddressCreateView.as_view(), name='checkout-create'),

    # url(r'^delete/$', csrf_exempt(views.AddressDeleteView.as_view()), name='delete'),
    # url(r'^delete/$', views.AddressDeleteView.as_view(), name='delete'),
    url(r'^delete/$', views.address_delete_view, name='delete'),
]

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_home, name='home'),
    url(r'^add/$', views.add_to_cart, name='add-list'),
    url(r'^update/$', views.UpdateCartView.as_view(), name='update'),  # Product Detail View
    url(r'^update-cart/$', views.cart_update_view, name='update-cart'),  # Update cart form
    url(r'^remove/$', views.cart_remove, name='remove'),
    url(r'^checkout/$', views.checkout_home, name='checkout'),
    url(r'^checkout/coupon/$', views.use_coupon_code, name='coupon'),
    url(r'^checkout/finalize/$', views.checkout_finalize, name='finalize'),
    url(r'^checkout/success/$', views.checkout_success, name='success'),
    url(r'^checkout/invoice/$', views.show_order_invoice, name='invoice'),
]

accounts/models.py
import os
import random
from datetime import timedelta
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db.models import Q
from django.db.models.signals import pre_save, post_save
from django.utils import timezone
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.template.loader import get_template

from oneoverthree.utils import random_string_generator, unique_key_generator, unique_slug_generator

DEFAULT_ACTIVATION_DAYS = getattr(settings, 'DEFAULT_ACTIVATION_DAYS', 1)


# Create your models here.
def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    new_filename = random.randint(1000000, 98495747363748)
    name, ext = get_filename_ext(filename)
    final_filename = f'{new_filename}{ext}'
    return f"accounts/{new_filename}/{final_filename}"


class UserManager(BaseUserManager):
    def create_user(self, email, mobile_number, first_name=None, last_name=None, password=None, is_active=False, is_admin=False, is_staff=False):
        if not email:
            raise ValueError("Must be a valid email address")
        if not password:
            raise ValueError("Must have password")

        user_obj = self.model(
            email=self.normalize_email(email),
            mobile_number=mobile_number,
            first_name=first_name,
            last_name=last_name,
        )
        user_obj.set_password(password)
        user_obj.staff = is_staff
        user_obj.admin = is_admin
        user_obj.is_active = is_active
        user_obj.save(using=self._db)
        return user_obj

    def create_staffuser(self, email, mobile_number, first_name=None, last_name=None, password=None):
        user = self.create_user(
            email,
            mobile_number=mobile_number,
            first_name=first_name,
            last_name=last_name,
            password=password,
            is_staff=True
        )
        return user

    def create_superuser(self, email, mobile_number, first_name=None, last_name=None, password=None):
        user = self.create_user(
            email,
            mobile_number=mobile_number,
            first_name=first_name,
            last_name=last_name,
            password=password,
            is_staff=True,
            is_admin=True
        )
        return user


class User(AbstractBaseUser):
    email           = models.EmailField(max_length=120, unique=True)
    mobile_number   = models.CharField(max_length=17, unique=True)
    first_name      = models.CharField(max_length=120, blank=True, null=True)
    last_name       = models.CharField(max_length=120, blank=True, null=True)
    image           = models.ImageField(upload_to=upload_image_path, blank=True,
                                        help_text='Field is optional.')
    is_active       = models.BooleanField(default=True)     # user can login
    admin           = models.BooleanField(default=False)    # superuser
    staff           = models.BooleanField(default=False)    # staff but not superuser
    editor          = models.BooleanField(default=False)    # user is editor
    has_store       = models.BooleanField(default=False)    # user is store owner
    timestamp       = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)
    # confirmed       = models.BooleanField(default=False)
    # confirmed_date  = models.DateTimeField(default=False)

    USERNAME_FIELD = 'email'

    # USERNAME_FIELD and password are required by default.
    REQUIRED_FIELDS = ['first_name', 'last_name', 'mobile_number']

    objects = UserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        if self.full_name:
            return self.full_name
        return self.email

    def get_short_name(self):
        return self.email

    def full_name(self):
        first_name = self.first_name
        last_name = self.last_name
        full_name = str(first_name + " " + last_name)
        return full_name

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def get_user_details(self):
        first_name = self.first_name
        last_name = self.last_name
        return "{full_name}\n{email}\n{mobile_num}".format(
            full_name=str(first_name + " " + last_name),
            email=self.email,
            mobile_num=self.mobile_number,
        )

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_editor(self):
        return self.editor


class EmailActivationQueryset(models.query.QuerySet):
    def confirmable(self):
        now = timezone.now()
        start_range = now - timedelta(days=DEFAULT_ACTIVATION_DAYS)
        end_range = now
        return self.filter(
            activated=False,
            forced_expired=False
        ).filter(
            timestamp__gt=start_range,
            timestamp__lte=end_range,
        )


class EmailActivationManager(models.Manager):
    #  Model Manager Functions

    def get_queryset(self):
        return EmailActivationQueryset(self.model, using=self.db)

    def confirmable(self):
        return self.get_queryset().confirmable()

    def all_confirmable(self):
        return self.get_queryset().all().confirmable()

    def email_exists(self, email):
        return self.get_queryset().filter(
            Q(email=email) | Q(user__email=email)
        ).filter(activated=False)


class EmailActivation(models.Model):
    user            = models.ForeignKey(User)
    email           = models.EmailField()
    key             = models.CharField(max_length=120, blank=True, null=True)
    coupon          = models.CharField(max_length=120, blank=True, null=True)
    activated       = models.BooleanField(default=False)
    forced_expired  = models.BooleanField(default=False)
    expires         = models.IntegerField(default=1)  # 24hrs
    timestamp       = models.DateTimeField(auto_now_add=True)
    update          = models.DateTimeField(auto_now=True)

    objects = EmailActivationManager()

    #  Model Instance Functions

    def __str__(self):
        return self.email

    def can_activate(self):
        qs = EmailActivation.objects.filter(pk=self.pk).confirmable()
        if qs.exists():
            return True
        return False

    def activate(self):
        if self.can_activate():
            #  Pre activation user signal
            user = self.user
            user.is_active = True
            user.save()
            #  Pre activation user signal for just activated
            self.activated = True
            self.save()
            return True
        return False

    def regenerate(self):
        self.key = None
        self.save()
        if self.key is not None:
            return True
        return False

    def send_activation_email(self):
        if not self.activated and not self.forced_expired:
            if self.key:
                base_url = getattr(settings, 'BASE_URL', 'https://www.1over3.store')
                key_path = reverse("account:email-activate", kwargs={'key': self.key})  # Use reverse
                path = "{base}{path}".format(base=base_url, path=key_path)
                context = {
                    'path': path,
                    'email': self.email,
                    'first_name': self.user.first_name
                }
                txt_    = get_template("registration/emails/verify.txt").render(context)
                html_   = get_template("registration/emails/verify.html").render(context)
                subject = '1-click Email Verification'
                from_email = settings.DEFAULT_FROM_EMAIL
                recipient_list = [self.email]
                sent_mail = send_mail(
                    subject,
                    txt_,
                    from_email,
                    recipient_list,
                    html_message=html_,
                    fail_silently=False,
                )
                return sent_mail
            return False

    def send_activated_email(self):
        base_url = getattr(settings, 'BASE_URL', 'https://www.1over3.store')
        if self.activated:
            context = {
                'code': self.coupon,
                'email': self.email,
                'first_name': self.user.first_name,
                'path': "{base}/{page}".format(base=base_url, page="outlet")
            }
            if self.coupon:
                txt_    = get_template("registration/emails/verified.txt").render(context)
                html_   = get_template("registration/emails/verified.html").render(context)
            else:
                txt_ = get_template("registration/emails/verified_noCoupon.txt").render(context)
                html_ = get_template("registration/emails/verified_noCoupon.html").render(context)
            subject = 'Welcome to 1OVER3'
            from_email = settings.DEFAULT_FROM_EMAIL
            recipient_list = [self.email]
            sent_mail = send_mail(
                subject,
                txt_,
                from_email,
                recipient_list,
                html_message=html_,
                fail_silently=False,
            )
            return sent_mail


def pre_save_email_activation(sender, instance, *args, **kwargs):
    if not instance.key and not instance.forced_expired:
        if not instance.key:
            instance.key = unique_key_generator(instance)


pre_save.connect(pre_save_email_activation, sender=EmailActivation)


def post_save_user_create_receiver(sender, instance, created, *args, **kwargs):
    if created:
        obj = EmailActivation.objects.create(user=instance, email=instance.email)

accounts/templates/accounts/base-auth.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>1OVER3 | Online fashion retail</title>
    {% include 'base/css.html' %}

</head>
<body>

<div class="limiter">
    <div class="container-login100">
        {% if messages %}
        <div class="container alert alert-success messages">
            {% for message in messages %}
            <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}<br/>
            </span>
            {% endfor %}
        </div>
        {% endif %}

        <div class="wrap-login100">
            {% block content %}

            {% endblock %}
            <div class="login100-more" style="background-image: url({% static 'img/bg-login.jpg' %});"></div>
        </div>
    </div>
</div>


<div id="dropDownSelect1"></div>

{% include 'base/js.html' %}


</body>
</html>

accounts/templates/accounts/home.html
{% extends "base.html" %}
{% load static %}


{% block content %}


<div class="container">

        <!-- Account Menu Header -->
        <!--<div class="col-12 col-md-5 col-lg-4 mt-4"  style="height: 500px">-->
        <div class="row">
            <div class="col-12 col-md-5 col-lg-4 mt-4">
                <div>
                    <h4 class="m-text23">
                        Account Overview
                    </h4>
                </div>
            </div>

            <!-- Account User Info -->
            <div class="col-12 col-md-7 col-lg-8 mt-4 mx-auto">
                <div class="row">
                    <!--SELLER DASHBOARD-->
                    {% if user.has_store %}
                    <div class="col-4 mr-auto">
                        <div class="size10 trans-0-2 m-t-10 ">
                            <!-- Link -->
                            <a class="flex-c-m h-full bo-rad-23 hov1 s-text1 trans-0-4 {% if request.path == '/account/dashboard/' %}bg5{% else %}bg1{% endif %}" href="{% url 'account:dashboard:home' %}">
                                Dashboard <span class="pl-2"><i class="fa fa-dashboard"></i></span>
                            </a>
                        </div>
                    </div>
                    {% endif %}

                    <div class="col-5 text-center ml-auto">
                        <div class="header-profile-name">
                            {{ user.full_name }}
                        </div>
                        <div class="header-profile-item-info">
                            {{ request.user }}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <!-- Account Menu Navigation -->
            <div class="col-12 col-md-4 mt-5 mt-md-0" >
                <div class="col-12 col-md-9 mr-auto">
                    <ul class="mt-0 mt-md-5">
                        <!--Account Details-->
                        <li class="p-t-6 p-b-8 bo6">
                            <a href="{% url 'account:details' %}" class="s-text13 p-t-5 p-b-5 {% if request.path == '/account/details/' %}active{% endif %}">
                                Personal Information
                            </a>
                        </li>

                        <!--Address Book-->
                        <li class="p-t-6 p-b-8 bo7">
                            <a href="{% url 'address:book' %}" class="s-text13 p-t-5 p-b-5 {% if request.path == '/account/address-book/' %}active{% endif %}">
                                Address Book
                            </a>
                        </li>

                        <!--Orders-->
                        <li class="p-t-6 p-b-8 bo7">
                            <a href="{% url 'account:orders' %}" class="s-text13 p-t-5 p-b-5 {% if request.path == '/account/orders/' %}active{% endif %}">
                                Orders
                            </a>
                        </li>

                        <!--Settings-->
                        <li class="p-t-6 p-b-8 bo7">
                            <a href="/account/settings/" class="s-text13 p-t-5 p-b-5 {% if request.path == '/account/settings/' %}active{% endif %}">
                                Settings
                            </a>
                        </li>

                        <!--Support-->
                        <li class="p-t-6 p-b-8 bo7">
                            <a href="/contact/" class="s-text13 p-t-5 p-b-5 {% if request.path == '/account/support/' %}active{% endif %}">
                                Support
                            </a>
                        </li>

                    </ul>
                </div>
            </div>

            <!--MAIN CONTENT-->
            <div class="col-12 col-md-8 mt-5 mt-md-4">
                <div class="d-none d-md-block">
                    <hr class="mt-md-4">
                </div>
                {% block panel %}
                <!--content-->
                {% endblock %}
            </div>
        </div>

        {% block flannel %} {% endblock %}


    <!--</div>-->
</div>


<!--<section class="relateproduct bgwhite p-t-45 p-b-138">-->
	<!--<div class="container">-->
		<!--<div class="sec-title p-b-60">-->
			<!--<h3 class="m-text5 t-center">-->
                <!--Account Analytics-->
            <!--</h3>-->
        <!--</div>-->

        <!--&lt;!&ndash; Card &ndash;&gt;-->
        <!--<div class="col-12 col-md-5 mx-auto">-->
            <!--<div class="card">-->
                <!--<div class="card-body">-->
                    <!--<h4 class="card-title">Viewed History</h4>-->
                    <!--<div class="list-group">-->
                        <!--<a class="list-group-item" href="{% url 'account:user-product-history' %}">Product</a>-->
                    <!--</div>-->

                <!--</div>-->
            <!--</div>-->
        <!--</div>-->
    <!--</div>-->
<!--</section>-->






{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base-auth.html' %}
{% load static %}

{% block content %}

<form class="login100-form validate-form" method='POST'>
    {% csrf_token %}
    <span class="login100-form-title p-b-34">
        Account Login
    </span>

    <!--Form-->
    <p>{{ form.non_field_errors.as_text }}</p>

    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field.errors }}
        {{ hidden_field }}
    {% endfor %}

    <div class="col-10 size13 bo4 m-b-12 mx-auto">
        <input class="sizefull s-text7 p-l-15 p-r-15" type="email" name="email" placeholder="Email" maxlength="120" required="" id="id_email">
    </div>
    {{ form.email.errors }}

    <div class="col-10 size13 bo4 m-b-12 mx-auto">
        <input class="sizefull s-text7 p-l-15 p-r-15" type="password" name="password" placeholder="Password" maxlength="120" required="" id="id_password">
    </div>
    {{ form.password.errors }}

    <div class="container-login100-form-btn">
        <div class="size14 trans-0-4 m-b-10">
            <!-- Button -->
            <button class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4">
                Sign in
            </button>
        </div>
    </div>

    <div class="w-full text-center p-t-27 p-b-239">
        <span class="txt1">
            Forgot
        </span>

        <a href="{% url 'password_reset' %}" class="txt2">
            User name / password?
        </a>
    </div>
    <div class="w-full text-center">
        <a href="{% url 'register' %}" class="txt3">
            Sign Up
        </a>
    </div>
</form>


{% endblock %}

accounts/templates/accounts/register.html
{% extends 'accounts/base-auth.html' %}
{% load static %}

{% block content %}

<form class="login100-form validate-form" method='POST'>
    {% csrf_token %}
    <span class="login100-form-title p-b-34">
        Account Register
    </span>

    <p>{{ form.non_field_errors.as_text }}</p>

    {% for hidden_field in form.hidden_fields %}
    {{ hidden_field.errors }}
    {{ hidden_field }}
    {% endfor %}

    <span class="s-text8 p-t-5 p-b-5">{{ form.first_name.errors }}</span>
    <div class="col-10 size13 bo4 m-b-12 mx-auto">
        {{ form.first_name }}
        <span class="s-text8 p-t-5 p-b-5">{{ form.first_name.help_text }}</span>
    </div>

    <span class="s-text8 p-t-5 p-b-5">{{ form.last_name.errors }}</span>
    <div class="col-10 size13 bo4 m-b-12 mx-auto">
        {{ form.last_name }}
        <span class="s-text8 p-t-5 p-b-5">{{ form.last_name.help_text }}</span>
    </div>

    <span class="txt2 s-text8 p-t-5">{{ form.email.errors }}</span>
    <div class="col-10 size13 bo4 m-b-12 mx-auto">
        {{ form.email }}
        <span class="s-text8 p-t-5 p-b-5">{{ form.email.help_text }}</span>
    </div>

    <span class="s-text8 p-t-5 p-b-5">{{ form.mobile_number.errors }}</span>
    <div class="col-10 size13 bo4 m-b-12 mx-auto">
        {{ form.mobile_number }}
        <span class="s-text8 p-t-5 p-b-5">{{ form.mobile_number.help_text }}</span>
    </div>

    <span class="s-text8 p-t-5 p-b-5">{{ form.password1.errors }}</span>
    <div class="col-10 size13 bo4 m-b-12 mx-auto">
        {{ form.password1 }}
        <span class="s-text8 p-t-5 p-b-5">{{ form.password1.help_text }}</span>
    </div>

    <span class="s-text8 p-t-5 p-b-5">{{ form.password2.errors }}</span>
    <div class="col-10 size13 bo4 m-b-12 mx-auto">
        {{ form.password2 }}
        <span class="s-text8 p-t-5 p-b-5">{{ form.password2.help_text }}</span>
    </div>

    <div class="container-login100-form-btn">
        <div class="size14 trans-0-4 m-b-10">
            <!-- Button -->
            <button class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4">
                Sign up
            </button>
        </div>
    </div>

    <div class="w-full text-center p-t-27 p-b-239">
        <!--<a href="{% url 'store_register' %}" class="txt2">-->
            <!--Apply for a Store?-->
        <!--</a>-->
        <span class="txt1">
            Apply for a Store?
        </span>

        <a href="{% url 'contact' %}" class="txt2">
            Send us a message!
        </a>
    </div>

    <div class="w-full text-center">
        <a href="{% url 'login' %}" class="txt5">
            Sign in
        </a>
    </div>
</form>



<!-- MODAL TO CROP THE IMAGE -->
<div class="modal fade" id="modalCrop" style="height: 100%;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Crop image</h4>
            </div>
            <div class="modal-body">
                <img src="" id="image" style="max-width: 75%; max-height: 75%;">
            </div>
            <div class="modal-footer">
                <div class="btn-group pull-left" role="group">
                    <button type="button" class="btn btn-default js-zoom-in">
                        <span class="glyphicon glyphicon-zoom-in"></span>
                    </button>
                    <button type="button" class="btn btn-default js-zoom-out">
                        <span class="glyphicon glyphicon-zoom-out"></span>
                    </button>
                </div>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" id="js-crop" class="btn btn-primary">Crop</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}




{% block js %}
<!--Crop Product Image-->
<script>
    $(function () {
        /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */

        // Opens modal for User profile image
        $(document).on('change','#id_image', function() {
            if (this.files && this.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#image").attr("src", e.target.result);
                    $("#js-crop").attr("class", "btn btn-primary js-crop-image");
                    $("#modalCrop").modal("show");

                };
                reader.readAsDataURL(this.files[0]);
            }
        });


        /* SCRIPTS TO HANDLE THE CROPPER BOX */
        var $image = $("#image");
        var cropBoxData;
        var canvasData;

        // Loads cropper box for User profile image
        $("#modalCrop").on("shown.bs.modal", function () {
            $image.cropper({
                viewMode: 1,
                aspectRatio: 1/1,
                minCropBoxWidth: 200,
                minCropBoxHeight: 200,
                ready: function () {
                    $image.cropper("setCanvasData", canvasData);
                    $image.cropper("setCropBoxData", cropBoxData);
                }
            });
        }).on("hidden.bs.modal", function () {
            cropBoxData = $image.cropper("getCropBoxData");
            canvasData = $image.cropper("getCanvasData");
            $image.cropper("destroy");
        });

        // Enable zoom in button
        $(".js-zoom-in").click(function () {
            $image.cropper("zoom", 0.1);
        });

        // Enable zoom out button
        $(".js-zoom-out").click(function () {
            $image.cropper("zoom", -0.1);
        });

        /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
        // Crops User profile image
        $(document).on('click','.js-crop-image', function() {
            var cropData = $image.cropper("getData");
            $("#id_x").val(cropData["x"]);
            $("#id_y").val(cropData["y"]);
            $("#id_height").val(cropData["height"]);
            $("#id_width").val(cropData["width"]);

            console.log("0");
            console.log($(cropData));
            console.log($(cropData["x"]));
            console.log($(cropData["y"]));
            console.log($(cropData["height"]));
            console.log($(cropData["width"]));

            // $("#productFormUpload").submit();
            $("#modalCrop").modal("hide");
        });

    });
</script>

{% endblock %}