cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_home, name='home'),
    url(r'^add/$', views.add_to_cart, name='add-list'),
    url(r'^update/$', views.UpdateCartView.as_view(), name='update'),  # Product Detail View
    url(r'^update-cart/$', views.cart_update_view, name='update-cart'),  # Update cart form
    url(r'^remove/$', views.cart_remove, name='remove'),
    url(r'^checkout/$', views.checkout_home, name='checkout'),
    url(r'^checkout/coupon/$', views.use_coupon_code, name='coupon'),
    url(r'^checkout/finalize/$', views.checkout_finalize, name='finalize'),
    url(r'^checkout/success/$', views.checkout_success, name='success'),
    url(r'^checkout/invoice/$', views.show_order_invoice, name='invoice'),
]

store/urls.py
from django.conf.urls import url

from . import views

app_name = 'store'

urlpatterns = [
    url(r'^$', views.StoreHomeView.as_view(), name='home'),
    url(r'^update-product/$', views.UpdateProductView.as_view(), name='update-product'),
    url(r'^product-review/$', views.ProductReviewFormView.as_view(), name='product-review'),
    url(r'^(?P<slug>[\w-]+)/$', views.CategoryView.as_view(), name='categories'),
    url(r'^category/(?P<slug>[\w-]+)/$', views.TagListView.as_view(), name='tags'),
    url(r'^(?P<slug1>[\w-]+)/(?P<slug2>[\w-]+)/$', views.ProductDetailSlugView.as_view(), name='detail'),
]

store/models.py
import random
import os
from datetime import timedelta
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.db.models import Q
from django.urls import reverse
from django.utils import timezone

from addresses.models import ProductWeight
from marketplace.models import Store
from oneoverthree.utils import unique_slug_generator, unique_sku_generator
from tags.models import Tag

from mptt.models import MPTTModel, TreeForeignKey

User = get_user_model()


# Create your models here.
def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    new_filename = random.randint(1000000, 98495747363748)
    name, ext = get_filename_ext(filename)
    final_filename = f'{new_filename}{ext}'
    return f"store/{new_filename}/{final_filename}"


class Category(MPTTModel):
    title = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=120, blank=True, unique=True)
    background_image = models.ImageField(upload_to=upload_image_path, blank=True, null=True)
    description = models.TextField(blank=True)
    ordering = models.IntegerField(blank=True)
    is_active = models.BooleanField(default=True)

    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    class Meta:
        verbose_name_plural = 'Categories'
        # unique_together = ('parent', 'slug')

    class MPTTMeta:
        order_insertion_by = ['ordering']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('store:categories', kwargs={'slug': self.slug})


def category_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)
    all_categories = Category.objects.all()
    if not instance.ordering:
        instance.ordering = all_categories.count() + 1


pre_save.connect(category_pre_save_receiver, sender=Category)


DISCOUNT_RATES = [(i*5, str(i*5)) for i in range(0, 12)]


class ProductQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(is_active=True)

    def featured(self):
        return self.filter(featured=True, is_active=True)

    def search(self, query):
        lookups = (
            Q(sku=query) |
            Q(title__icontains=query) |
            Q(description__icontains=query) |
            Q(tags__title__icontains=query)
        )
        return self.filter(lookups).distinct()


class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    def check_new_in(self, store):
        qs = self.all().filter(store=store)
        if qs.count() > 0:
            for product in qs:
                if product.new_in:
                    timestamp = product.timestamp
                    now = timezone.now()
                    # valid_days = timedelta(days=7)
                    life_span = now - timestamp
                    if life_span.days > 10:
                        print("Scream")
                        product.new_in = False
                        product.save()

    def all(self):
        return self.get_queryset().active()

    def featured(self):
        return self.get_queryset().featured()

    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id)  # Product.objects == self.get_querset
        if qs.count() == 1:
            return qs.first()
        return None

    def search_store(self, query, store_slug):
        return self.get_queryset().search(query).filter(store__slug=store_slug)

    def search_site(self, query):
        return self.get_queryset().search(query)


class Product(models.Model):
    title               = models.CharField(max_length=120, )
    slug                = models.SlugField(max_length=120, blank=True, unique=True)
    sku                 = models.CharField(max_length=120, blank=True, unique=True)
    product_type        = models.ForeignKey(ProductWeight, default=0.7,
                                  help_text='For calculating shipping cost', null=True)
    store               = TreeForeignKey(Store, related_name='products', default=None, null=True)
    category            = TreeForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    brand               = models.CharField(max_length=120, blank=True)
    description         = models.TextField()
    extra_description   = models.TextField(blank=True, help_text="Additional Information, Care tips?")
    tags                = models.ManyToManyField(Tag, related_name='products')
    base_price          = models.DecimalField(decimal_places=2, max_digits=10, default=00.00)
    price               = models.DecimalField(decimal_places=2, max_digits=10, blank=True)
    image_a             = models.ImageField(upload_to=upload_image_path, null=False,
                                            help_text="First image displayed to customers")
    image_b             = models.ImageField(upload_to=upload_image_path, null=False,
                                            help_text="Second image displayed to customers")
    image_c             = models.ImageField(upload_to=upload_image_path, null=False,
                                            help_text="Third image displayed to customers")
    has_variants        = models.BooleanField(default=False)
    featured            = models.BooleanField(default=False)
    new_in              = models.BooleanField(default=False)
    on_sale             = models.BooleanField(default=False)
    is_active           = models.BooleanField(default=True)
    discount            = models.PositiveIntegerField(blank=True, null=True, choices=DISCOUNT_RATES,
                                                      help_text="Percentage '%' discount")
    stock               = models.PositiveIntegerField(blank=True, null=True,
                                                      help_text="Overwritten if variants")
    timestamp           = models.DateTimeField(auto_now_add=True)

    objects = ProductManager()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['pk']

    def get_absolute_url(self):
        if self.store.slug == "1over3":
            return reverse("store:detail", kwargs={'slug1': str(self.category).lower(), 'slug2': self.slug})
        else:
            return reverse("marketplace:product-detail", kwargs={'slug1': self.store.slug, 'slug2': self.slug})

    @property
    def name(self):
        return self.title


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

    if instance.sku == "":
        instance.sku = unique_sku_generator(instance)

    if not instance.price:
        instance.price = instance.base_price

    if not instance.on_sale:
        instance.price = instance.base_price

    if instance.discount:
        base_price = instance.base_price
        discount = instance.discount
        discounted_amount = (discount * base_price) / 100
        # discounted_amount = discount_rate * base_price
        new_price = base_price - discounted_amount
        instance.price = new_price
        instance.on_sale = True


pre_save.connect(product_pre_save_receiver, sender=Product)


class ProductImage(models.Model):
    file = models.ImageField(upload_to=upload_image_path, null=True, blank=True,
                              help_text="First image displayed to customers")
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.product)

    class Meta:
        ordering = ['pk']


class ProductReview(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    content = models.TextField(max_length=600, help_text="Enter product review here.")
    is_active = models.BooleanField(default=True)
    is_anonymous = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["timestamp"]

    def __str__(self):
        """
        String for representing the Model object.
        """
        len_title = 75
        if len(self.content) > len_title:
            title_string = self.content[:len_title] + '...'
        else:
            title_string = self.content
        return title_string


QUANTITY_CHOICES = [(i, str(i)) for i in range(0, 26)]

SIZE_CHOICES = (
    ('S', 'S'),
    ('M', 'M'),
    ('L', 'L'),
    ('XL', 'XL'),
    ('38', '38'),
    ('39', '39'),
    ('40', '40'),
    ('41', '41'),
    ('42', '42'),
    ('43', '43'),
    ('44', '44'),
    ('45', '45'),
    ('W-30', 'W-30'),
    ('W-32', 'W-32'),
    ('W-34', 'W-34'),
    ('W-36', 'W-36'),
)


class VariationManager(models.Manager):
    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id)
        if qs.count() == 1:
            return qs.first()
        return None

    def get_size(self, product_obj, size_id):
        if size_id:
            size = Variation.objects.get_by_id(id=size_id)
            stock = size.quantity
        else:
            size = '---'
            stock = product_obj.stock

        return size, stock


class Variation(models.Model):
    size        = models.CharField(max_length=120, choices=SIZE_CHOICES,
                                   blank=True, help_text='select a size.')
    product     = models.ForeignKey(Product, null=True)
    quantity       = models.PositiveIntegerField(null=True, choices=QUANTITY_CHOICES)
    is_active   = models.BooleanField(default=True)

    objects = VariationManager()

    def __str__(self):
        return str(self.size)

store/templates/store/snippets/product_detail/add-product-detail.html
<form class="form-product-ajax" method="POST" action="{% url 'cart:update' %}" data-endpoint="{% url 'cart:update' %}">
    {% csrf_token %}
    <!--{{ form }}-->
    <div class="p-t-33 p-b-60">
        <!--Size-->
        {% if product.has_variants is True %}
        <div class="flex-m flex-w p-b-10">
            {{ sizes.non_field_errors }}

            {% for hidden_field in sizes.hidden_fields %}
            {{ hidden_field.errors }}
            {{ hidden_field }}
            {% endfor %}

            {% for field in sizes.visible_fields %}
            <div class="s-text15 w-size15 t-center">
                {{ field.label_tag }}
            </div>

            {{ field.errors }}
            <div class="w-size16">
                <div class="form-group">
                    {{ field }}
                </div>
            </div>

            <div class="row">
                <span class="col-12  s-text8 p-t-5 p-b-5">
                    {{ field.help_text }}
                </span>
            </div>
            {% endfor %}
        </div>
        {% endif %}

        <div class="flex-r-m flex-w p-t-10">
            <div class="w-size16 flex-m flex-w">
                <div class="flex-w bo5 of-hidden m-r-22 m-t-10 m-b-10">
                    <button class="btn-num-product-down color1 flex-c-m size7 bg8 eff2">
                        <i class="fs-12 fa fa-minus" aria-hidden="true"></i>
                    </button>

                    <input type="hidden" name="product_id" id="id_product_id"  value="{{ product.id }}" />
                    <input type="number" class="size8 m-text18 t-center num-product" name="product_quantity" id="id_quantity" value="1"/>


                    <button class="btn-num-product-up color1 flex-c-m size7 bg8 eff2">
                        <i class="fs-12 fa fa-plus" aria-hidden="true"></i>
                    </button>
                </div>

                <div class=" product-detail-addcart size9 trans-0-4 m-t-10 m-b-10">
                    <!-- Button -->
                    <button class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4" type="submit">
                        Add to Cart
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>

<!-- Container Selection -->
	<div id="dropDownSelect1"></div>
	<!--<div id="dropDownSelect2"></div>-->

store/templates/store/snippets/product_detail/breadcrumb.html
<div class="bread-crumb bgwhite flex-w p-l-52 p-r-15 p-t-30 p-l-15-sm">
    <a href="{{ home_url }}" class="s-text16">
        Home
        <i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
    </a>

    <a href="{{ store_url }}" class="s-text16">
        Women
        <i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
    </a>

    <a href="#" class="s-text16">
        T-Shirt
        <i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
    </a>

    <span class="s-text17">
			Boxy T-Shirt with Roll Sleeve Detail
		</span>
</div>

store/templates/store/snippets/product_detail/product-image-display.html
{% load static %}

<div class="wrap-slick3 flex-sb flex-w">
    <div class="wrap-slick3-dots"></div>

    <div class="slick3">
        <div class="item-slick3" data-thumb="{{ object.image_a.url }}">
            <div class="wrap-pic-w">
                <img src="{{ object.image_a.url }}" alt="IMG-PRODUCT">
            </div>
        </div>
        {% if object.image_b %}
        <div class="item-slick3" data-thumb="{{ object.image_b.url }}">
            <div class="wrap-pic-w">
                <img src="{{object.image_b.url }}" alt="IMG-PRODUCT">
            </div>
        </div>
        {% endif %}
        {% if object.image_b %}
        <div class="item-slick3" data-thumb="{{ object.image_c.url }}">
            <div class="wrap-pic-w">
                <img src="{{ object.image_c.url }}" alt="IMG-PRODUCT">
            </div>
        </div>
        {% endif %}
    </div>
</div>

store/templates/store/snippets/product_detail/related-product.html
<section class="relateproduct bgwhite p-t-45 p-b-138">
    <div class="container">
        <div class="sec-title p-b-60">
            <h3 class="m-text5 t-center">
                Related Products
            </h3>
        </div>

        <!-- Slide2 -->
        <div class="wrap-slick2">
            <div class="slick2">

                <div class="item-slick2 p-l-15 p-r-15">
                    <!-- Block2 -->
                    <div class="block2">
                        <div class="block2-img wrap-pic-w of-hidden pos-relative">
                            <img src="{{ instance.image_a.url }}" alt="IMG-PRODUCT">

                            <div class="block2-overlay trans-0-4">
                                <form class="form-product-ajax block2-btn-addcart w-size1 trans-0-4" method='POST' action="{% url 'cart:add' %}" data-endpoint="{% url 'cart:add' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="product_id" value="{{ instance.id }}" />
                                    <button class="flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4">
                                        Add to Cart
                                    </button>
                                </form>
                            </div>
                        </div>

                        <div class="block2-txt p-t-20">
                            <a href="{{ instance.get_absolute_url }}" class="block2-name dis-block s-text3 p-b-5">
                                {{ instance.title }}
                            </a>

                            <span class="block2-price m-text6 p-r-5">₦{{ instance.price }}</span>

                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
</section>