cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_home, name='home'),
    url(r'^add/$', views.add_to_cart, name='add-list'),
    url(r'^update/$', views.UpdateCartView.as_view(), name='update'),  # Product Detail View
    url(r'^update-cart/$', views.cart_update_view, name='update-cart'),  # Update cart form
    url(r'^remove/$', views.cart_remove, name='remove'),
    url(r'^checkout/$', views.checkout_home, name='checkout'),
    url(r'^checkout/coupon/$', views.use_coupon_code, name='coupon'),
    url(r'^checkout/finalize/$', views.checkout_finalize, name='finalize'),
    url(r'^checkout/success/$', views.checkout_success, name='success'),
    url(r'^checkout/invoice/$', views.show_order_invoice, name='invoice'),
]

dashboard/urls.py
from django.conf.urls import url

from . import views


app_name = 'dashboard'

urlpatterns = [
    url(r'^$', views.DashboardHomeView.as_view(), name='home'),

    url(r'^orders/$', views.DashboardOrdersView.as_view(), name='orders'),
    url(r'^product-list/$', views.DashboardProductListView.as_view(), name='products'),
    url(r'^store-image-upload/$', views.StoreImageUploadView.as_view(), name='update-store-image'),
    url(r'^add-product/$', views.AddProductView.as_view(), name='add-product'),
    url(r'^update-product/$', views.UpdateProductFormView.as_view(), name='update-product'),
    url(r'^delete-product/$', views.DeleteProductView.as_view(), name='delete-product'),
    url(r'^order-processing/$', views.OrderProcessingView.as_view(), name='order-processing'),
    url(r'^order-shipped/$', views.OrderShippedView.as_view(), name='order-shipped'),
]

store/urls.py
from django.conf.urls import url

from . import views

app_name = 'store'

urlpatterns = [
    url(r'^$', views.StoreHomeView.as_view(), name='home'),
    url(r'^update-product/$', views.UpdateProductView.as_view(), name='update-product'),
    url(r'^product-review/$', views.ProductReviewFormView.as_view(), name='product-review'),
    url(r'^(?P<slug>[\w-]+)/$', views.CategoryView.as_view(), name='categories'),
    url(r'^category/(?P<slug>[\w-]+)/$', views.TagListView.as_view(), name='tags'),
    url(r'^(?P<slug1>[\w-]+)/(?P<slug2>[\w-]+)/$', views.ProductDetailSlugView.as_view(), name='detail'),
]

dashboard/models.py
from decimal import Decimal
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import pre_save, post_save

from marketplace.models import Store
from orders.models import OrderItem
from store.models import Product


# Create your models here.
User = get_user_model()

STAFF_CHOICE_FIELD = (
    ('brand', 'Brand'),
    ('retailer', 'Retailer'),
    ('creative', 'Creative'),
)


class DashboardQuerySet(models.query.QuerySet):
    def all(self):
        return self.filter(is_active=True)


class DashboardManager(models.Manager):
    def get_queryset(self):
        return DashboardQuerySet(self.model, using=self._db)

    def get_dashboard(self, store):
        qs = self.get_queryset().all().filter(store=store)
        if qs.count() == 1:
            dashboard = qs.first()
            # print(dashboard)
            return dashboard

    def pending_orders(self, store):
        order_items = OrderItem.objects.all().filter(store=store, is_active=True)
        pending_orders = []
        for item in order_items:
            if item.status == 'pending':
                pending_orders.append(item)

        dashboard = self.get_dashboard(store)
        dashboard.orders = len(pending_orders)
        dashboard.save()
        return pending_orders

    def processing_orders(self, store):
        dashboard = self.get_dashboard(store)
        order_items = OrderItem.objects.all().filter(store=store, is_active=True)
        processing_orders = []
        for item in order_items:
            if item.status == 'processing':
                processing_orders.append(item)
        return processing_orders

    def completed_orders(self, store):
        dashboard = self.get_dashboard(store)
        order_items = OrderItem.objects.all().filter(store=store)
        completed_orders = []
        for item in order_items:
            if item.status in ('shipped', 'completed'):
                completed_orders.append(item)
        return completed_orders

    def all_time_sales(self, store):
        order_items = OrderItem.objects.all().filter(
            store=store,
            is_active=True,
            status='completed'
        )
        dashboard = self.get_dashboard(store)
        dashboard.sales = order_items.count()
        revenue = [item.price for item in order_items]
        total_revenue = sum(revenue)
        dashboard.total_revenue = total_revenue
        dashboard.save()

    # def order_shipped(self, email):


class Dashboard(models.Model):
    store = models.ForeignKey(Store, related_name='dashboard', on_delete=models.SET_NULL, null=True)
    total_revenue = models.DecimalField(decimal_places=2, max_digits=10, default=00.00)
    sales = models.IntegerField(default=0)
    orders = models.IntegerField(default=0)
    tariff = models.DecimalField(decimal_places=2, max_digits=10, default=0.10)
    balance = models.DecimalField(decimal_places=2, max_digits=10, default=00.00)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    objects = DashboardManager()

    def __str__(self):
        return str(self.store)


def store_post_save_receiver(sender, instance, *args, **kwargs):
    Dashboard.objects.get_or_create(
        store=instance
    )


post_save.connect(store_post_save_receiver, sender=Store)

dashboard/forms.py
from io import BytesIO
from django.core.files.base import ContentFile
from django import forms
from PIL import Image

from .models import Store


class StoreSliderUploadForm(forms.Form):
    slider_image = forms.ImageField(widget=forms.ClearableFileInput(), required=False)
    x_1 = forms.FloatField(widget=forms.HiddenInput())
    y_1 = forms.FloatField(widget=forms.HiddenInput())
    width_1 = forms.FloatField(widget=forms.HiddenInput())
    height_1 = forms.FloatField(widget=forms.HiddenInput())

    def save(self, *args, **kwargs):
        data = self.data
        store = kwargs.get('store')

        store_slider_image = store.slider_image
        ext = str(store_slider_image).split('.', 1)[1]

        x = float(data.get('x_1'))
        y = float(data.get('y_1'))
        w = float(data.get('width_1'))
        h = float(data.get('height_1'))

        if store_slider_image:
            buffer = BytesIO()
            ext = 'JPEG' if ext.lower() == 'jpg' else ext.upper()
            image = Image.open(store_slider_image)
            cropped_image = image.crop((x, y, w+x, h+y))
            resized_image = cropped_image.resize((1921, 998), Image.ANTIALIAS)
            resized_image.save(buffer, ext, quality=100)
            img_content = ContentFile(buffer.getvalue(), store_slider_image.name)

            store.slider_image.save(store_slider_image.name, img_content, save=False)


class StoreHeaderUploadForm(forms.ModelForm):
    header_image = forms.ImageField(widget=forms.ClearableFileInput(), required=False)
    x_2 = forms.FloatField(widget=forms.HiddenInput())
    y_2 = forms.FloatField(widget=forms.HiddenInput())
    width_2 = forms.FloatField(widget=forms.HiddenInput())
    height_2 = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Store
        fields = ('header_image', )

    def save(self, *args, **kwargs):
        data = self.data
        store = kwargs.get('store')

        store_header_image = store.header_image
        ext = str(store_header_image).split('.', 1)[1]

        x = float(data.get('x_2'))
        y = float(data.get('y_2'))
        w = float(data.get('width_2'))
        h = float(data.get('height_2'))

        if store_header_image:
            buffer = BytesIO()
            ext = 'JPEG' if ext.lower() == 'jpg' else ext.upper()
            image = Image.open(store_header_image)
            cropped_image = image.crop((x, y, w+x, h+y))
            resized_image = cropped_image.resize((1920, 960), Image.ANTIALIAS)
            resized_image.save(buffer, ext, quality=100)
            img_content = ContentFile(buffer.getvalue(), store_header_image.name)

            store.header_image.save(store_header_image.name, img_content, save=False)

store/forms.py
from io import BytesIO
from django import forms
from django.forms import formset_factory
from django.core.files.base import ContentFile
from PIL import Image

from .models import Product, ProductReview, Variation


# Enter your forms here.
class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = ProductReview
        fields = {
            'author', 'product', 'is_anonymous',
        }


class UpdateProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = (
            'title', 'store', 'product_type', 'category',
            'description', 'extra_description', 'tags',
            'base_price', 'image_a', 'image_b', 'image_c',
            'stock', 'featured', 'has_variants', 'discount'
        )
        labels = {"featured": "Set as featured"}

    def __init__(self, *args, **kwargs):
        super(UpdateProductForm, self).__init__(*args, **kwargs)
        # initial_arguments = kwargs.get('initial', None)
        # print(initial_arguments)
        for field in iter(self.fields):
            if field in ('featured', 'has_variants'):
                pass
            else:
                self.fields[field].widget.attrs.update({
                    'class': 'form-control',
                })

    def save(self, commit=True):
        product = super(UpdateProductForm, self).save(commit=False)
        if commit:
            product.save()
        return product


class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = (
            'store', 'title', 'product_type', 'category', 'brand',
            'description', 'extra_description', 'tags', 'base_price',
            'image_a', 'image_b', 'image_c',
            'stock', 'featured'
        )

    def __init__(self, *args, **kwargs):
        super(AddProductForm, self).__init__(*args, **kwargs)
        self.fields['tags'].widget.attrs.update({'class': 'js-example-basic-multiple'})
        for field in iter(self.fields):
            if field in ('featured', 'has_variants'):
                pass
            elif field in ('category', 'product_type'):
                self.fields[field].widget.attrs.update({
                    'class': 'size13 bo4 py-0 m-text18',
                })

            else:
                self.fields[field].widget.attrs.update({
                    'class': 'form-control m-text18'
                })
        # Help Text
        self.fields['stock'].help_text = 'Overwritten if product has variants'

    def clean(self):
        print(self.data)
        if self.errors:
            print(self.errors)
        print(self.cleaned_data)

    def save(self, commit=True):
        product = super(AddProductForm, self).save(commit=False)
        if commit:
            product.save()
        return product


class ImageAUploadForm(forms.Form):
    x_1 = forms.FloatField(widget=forms.HiddenInput())
    y_1 = forms.FloatField(widget=forms.HiddenInput())
    width_1 = forms.FloatField(widget=forms.HiddenInput())
    height_1 = forms.FloatField(widget=forms.HiddenInput())

    def save(self, product, *args, **kwargs):
        data = self.data

        product_image = product.image_a
        ext = str(product_image).split('.', 1)[1]

        x = float(data.get('x_1'))
        y = float(data.get('y_1'))
        w = float(data.get('width_1'))
        h = float(data.get('height_1'))

        if product_image:
            buffer = BytesIO()
            ext = 'JPEG' if ext.lower() == 'jpg' else ext.upper()
            image = Image.open(product_image)
            cropped_image = image.crop((x, y, w+x, h+y))
            resized_image = cropped_image.resize((480, 720), Image.ANTIALIAS)
            resized_image.save(buffer, ext, quality=100)
            img_content = ContentFile(buffer.getvalue(), product_image.name)

            product.image_a.save(product_image.name, img_content, save=False)


class ImageBUploadForm(forms.Form):
    x_2 = forms.FloatField(widget=forms.HiddenInput())
    y_2 = forms.FloatField(widget=forms.HiddenInput())
    width_2 = forms.FloatField(widget=forms.HiddenInput())
    height_2 = forms.FloatField(widget=forms.HiddenInput())

    def save(self, product, *args, **kwargs):
        data = self.data
        product_image = product.image_b
        ext = str(product_image).split('.', 1)[1]

        x = float(data.get('x_2'))
        y = float(data.get('y_2'))
        w = float(data.get('width_2'))
        h = float(data.get('height_2'))

        if product_image:
            buffer = BytesIO()
            ext = 'JPEG' if ext.lower() == 'jpg' else ext.upper()
            image = Image.open(product_image)
            cropped_image = image.crop((x, y, w + x, h + y))
            resized_image = cropped_image.resize((480, 720), Image.ANTIALIAS)
            resized_image.save(buffer, ext, quality=100)
            img_content = ContentFile(buffer.getvalue(), product_image.name)

            product.image_b.save(product_image.name, img_content, save=False)


class ImageCUploadForm(forms.Form):
    x_3 = forms.FloatField(widget=forms.HiddenInput())
    y_3 = forms.FloatField(widget=forms.HiddenInput())
    width_3 = forms.FloatField(widget=forms.HiddenInput())
    height_3 = forms.FloatField(widget=forms.HiddenInput())

    def save(self, product, *args, **kwargs):
        data = self.data
        product_image = product.image_c
        ext = str(product_image).split('.', 1)[1]

        x = float(data.get('x_3'))
        y = float(data.get('y_3'))
        w = float(data.get('width_3'))
        h = float(data.get('height_3'))

        if product_image:
            buffer = BytesIO()
            ext = 'JPEG' if ext.lower() == 'jpg' else ext.upper()
            image = Image.open(product_image)
            cropped_image = image.crop((x, y, w+x, h+y))
            resized_image = cropped_image.resize((480, 720), Image.ANTIALIAS)
            resized_image.save(buffer, ext, quality=100)
            img_content = ContentFile(buffer.getvalue(), product_image.name)

            product.image_c.save(product_image.name, img_content, save=False)


class ProductVariationForm(forms.ModelForm):
    class Meta:
        model = Variation
        fields = (
            'size', 'quantity'
        )

    def __init__(self, *args, **kwargs):
        super(ProductVariationForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class': 'form-control'})

    def save(self, *args, **kwargs):
        variant = super(ProductVariationForm, self).save(commit=False)
        product = kwargs.get('product')
        if variant:
            variant.product = product
            return variant


ProductVariationFormSet = formset_factory(ProductVariationForm, extra=5, max_num=5)


class SizeVariationForm(forms.ModelForm):
    class Meta:
        model = Variation
        fields = ('product',)  # , 'quantity', 'size', )
        labels = {"product": "size"}

    def __init__(self, product, *args, **kwargs):
        super(SizeVariationForm, self).__init__(*args, **kwargs)
        self.fields['product'].queryset = Variation.objects.filter(product=product)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

dashboard/templates/dashboard/product_list.html
{% extends "accounts/home.html" %}
{% load static %}

{% block header %}
{{ form.tags.media.css }}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.10/select2-bootstrap.css">
{% endblock %}


{% block panel %}
<div class="m-b-100">
    <ul class="nav nav-pills" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'account:dashboard:home' %}" role="tab" aria-selected="false">Statistics</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'account:dashboard:orders' %}" role="tab" aria-selected="false">Orders</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" id="product-list-tab" data-toggle="tab" href="#product-list" role="tab" aria-controls="product-list" aria-selected="true">Products</a>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">
        <!--Store Statistics-->

        <!--Orders Tab-->

        <!--Product List Tab-->
        <div class="tab-pane fade show active" id="product-list" role="tabpanel" aria-labelledby="product-list-tab">
            <div class="container">
                <div class="row">
                    <!--<div class="d-none d-md-block">-->
                        <hr class="mt-md-4">
                    <!--</div>-->
                    <div class="col-12 col-md-6 mt-4 ">
                        <h5 class="m-text20 "> All listed products </h5>
                    </div>

                    <!-- Pagination Breadcrumb -->
                    <span class="col-12 text-right s-text8  p-b-10">
                        Showing {{ products.start_index }} – {{ products.end_index }} of {{ paginator.count }} results
                    </span>

                    {% for product in products %}
                    <div class="col-12 col-md-6 mt-1 ">
                        <div class="row">
                            <a href="{{ product.get_absolute_url }}" class="dis-block wrap-pic-w w-size22 m-r-20 trans-0-4 hov4">
                                <img src="{{ product.image_a.url }}" alt="IMG-PRODUCT">
                            </a>

                            <div class="w-size23 p-t-5">
                                <a href="{{ product.get_absolute_url }}" class="s-text20">
                                    {{ product.title }}
                                </a>

                                <span class="dis-block s-text17 p-t-6">
                                    ₦{{ product.price }}
                                </span>

                                <div class="row mt-2">
                                    <!--Product Stock-->
                                    <span class="col-5 s-text17">
                                        Stock: {{ product.stock }}
                                    </span>

                                    <!--Update Product-->
                                    <div class="col-2">
                                        <form method="POST" action="{% url 'store:update-product' %}">
                                            {% csrf_token %}
                                            <input type='hidden' name='product_id' value='{{ product.id }}' />
                                            <button class="btn btn-white btn-md mb-2" type="submit"><i class="fa fa-edit"></i></button>
                                        </form>
                                    </div>

                                    <!--Delete Product-->
                                    <div class="col-2">
                                        <form method="POST" action="{% url 'account:dashboard:delete-product' %}">
                                            {% csrf_token %}
                                            <input type='hidden' name='product_id' value='{{ product.id }}' />
                                            <button class="btn btn-white btn-md mb-2" type="submit"><i class="fa fa-trash"></i></button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                    <!-- Pagination Breadcrumb -->
                    <span class="col-12 text-right s-text8 p-t-15 p-b-10">
                        Showing {{ products.start_index }} – {{ products.end_index }} of {{ paginator.count }} results
                    </span>

                    <!-- Pagination -->
                    {% if products.has_other_pages %}
                    <div class="pagination flex-m flex-w p-t-26">
                        <!--<a href="#" class="item-pagination flex-c-m trans-0-4 active-pagination">1</a>-->
                        <!--<a href="#" class="item-pagination flex-c-m trans-0-4">2</a>-->
                        {% for i in products.paginator.page_range %}
                        {% if products.number == i %}
                        <a href="#" class="item-pagination flex-c-m trans-0-4 active-pagination">{{ i }}</a>
                        {% else %}
                        <a href="?page={{ i }}" class="item-pagination flex-c-m trans-0-4">{{ i }}</a>
                        {% endif %}
                        {% endfor %}
                    </div>
                    {% endif %}

                    <!--Add New Product-->
                    <div class="col-12 m-t-35 m-b-10">
                        <div class="size10 trans-0-2 ">
                            <!-- Link -->
                            <a class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4" href="{% url 'account:dashboard:add-product' %}">
                                New Product +
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}



{% block flannel %}

    <!-- MODAL TO CROP THE IMAGE -->
    <div class="modal fade" id="modalCrop" style="height: 100%;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Crop image</h4>
                </div>
                <div class="modal-body">
                    <img src="" id="image" style="max-width: 100%;">
                </div>
                <div class="modal-footer">
                    <div class="btn-group pull-left" role="group">
                        <button type="button" class="btn btn-default js-zoom-in">
                            <span class="glyphicon glyphicon-zoom-in"></span>
                        </button>
                        <button type="button" class="btn btn-default js-zoom-out">
                            <span class="glyphicon glyphicon-zoom-out"></span>
                        </button>
                    </div>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="button" id="js-crop" class="btn btn-primary">Crop</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}




<!--Block JS-->
{% block js %}

<!--Crop Product Image-->
<script>
    $(function () {
        /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */

        // Opens modal for image file A
        $(document).on('change','#id_image_a', function() {
            if (this.files && this.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#image").attr("src", e.target.result);
                    $("#js-crop").attr("class", "btn btn-primary js-crop-image-a");
                    // $( "#js-crop" ).toggleClass( "js-crop-image-a" )
                    $("#modalCrop").modal("show");

                };
                reader.readAsDataURL(this.files[0]);
            }
        });

        // Opens modal for image file B
        $(document).on('change','#id_image_b', function() {
            if (this.files && this.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#image").attr("src", e.target.result);
                    $("#js-crop").attr("class", "btn btn-primary js-crop-image-b");
                    $("#modalCrop").modal("show");
                }
                reader.readAsDataURL(this.files[0]);
            }
        });

        // Opens modal for image file C
        $(document).on('change','#id_image_c', function() {
            if (this.files && this.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    // $("#js-crop").toggleClass( "js-crop-image-c" )
                    $("#image").attr("src", e.target.result);
                    $("#js-crop").attr("class", "btn btn-primary js-crop-image-c");
                    $("#modalCrop").modal("show");
                }
                reader.readAsDataURL(this.files[0]);
            }
        });

        // Opens modal for image file
        $(document).on('change','#id_file', function() {
            if (this.files && this.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#image").attr("src", e.target.result);
                    $("#js-crop").attr("class", "btn btn-primary js-crop-image");
                    $("#modalCrop").modal("show");
                }
                reader.readAsDataURL(this.files[0]);
            }
        });


        /* SCRIPTS TO HANDLE THE CROPPER BOX */
        var $image = $("#image");
        var cropBoxData;
        var canvasData;
        $("#modalCrop").on("shown.bs.modal", function () {
            $image.cropper({
                viewMode: 1,
                aspectRatio: 2/3,
                minCropBoxWidth: 240,
                minCropBoxHeight: 360,
                ready: function () {
                    $image.cropper("setCanvasData", canvasData);
                    $image.cropper("setCropBoxData", cropBoxData);
                }
            });
        }).on("hidden.bs.modal", function () {
            cropBoxData = $image.cropper("getCropBoxData");
            canvasData = $image.cropper("getCanvasData");
            $image.cropper("destroy");
        });

        // Enable zoom in button
        $(".js-zoom-in").click(function () {
            $image.cropper("zoom", 0.1);
        });

        // Enable zoom out button
        $(".js-zoom-out").click(function () {
            $image.cropper("zoom", -0.1);
        });

        /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */

        // Crops image file A
        $(document).on('click','.js-crop-image-a', function() {
            var cropData = $image.cropper("getData");
            $("#id_x_1").val(cropData["x"]);
            $("#id_y_1").val(cropData["y"]);
            $("#id_height_1").val(cropData["height"]);
            $("#id_width_1").val(cropData["width"]);

            console.log("a");
            console.log($(cropData));
            console.log($(cropData["x"]));
            console.log($(cropData["y"]));
            console.log($(cropData["height"]));
            console.log($(cropData["width"]));

            // $("#productFormUpload").submit();
            $("#modalCrop").modal("hide");
        });

        // Crops image file B
        $(document).on('click','.js-crop-image-b', function() {
            var cropData = $image.cropper("getData");
            $("#id_x_2").val(cropData["x"]);
            $("#id_y_2").val(cropData["y"]);
            $("#id_height_2").val(cropData["height"]);
            $("#id_width_2").val(cropData["width"]);

            console.log("b");
            console.log($(cropData));
            console.log($(cropData["x"]));
            console.log($(cropData["y"]));
            console.log($(cropData["height"]));
            console.log($(cropData["width"]));

            // $("#productFormUpload").submit();
            $("#modalCrop").modal("hide");
        });

        // Crops image file C
        $(document).on('click','.js-crop-image-c', function() {
            var cropData = $image.cropper("getData");
            $("#id_x_3").val(cropData["x"]);
            $("#id_y_3").val(cropData["y"]);
            $("#id_height_3").val(cropData["height"]);
            $("#id_width_3").val(cropData["width"]);

            console.log("c");
            console.log($(cropData));
            console.log($(cropData["x"]));
            console.log($(cropData["y"]));
            console.log($(cropData["height"]));
            console.log($(cropData["width"]));

            // $("#productFormUpload").submit();
            $("#modalCrop").modal("hide");
        });

        // Crops image file
        $(document).on('click','.js-crop-image', function() {
            var cropData = $image.cropper("getData");
            $("#id_x").val(cropData["x"]);
            $("#id_y").val(cropData["y"]);
            $("#id_height").val(cropData["height"]);
            $("#id_width").val(cropData["width"]);

            console.log("0");
            console.log($(cropData));
            console.log($(cropData["x"]));
            console.log($(cropData["y"]));
            console.log($(cropData["height"]));
            console.log($(cropData["width"]));

            // $("#productFormUpload").submit();
            $("#modalCrop").modal("hide");
        });
    });
</script>

{% endblock %}